##########################
#
# Makefile with Comments
#
# June 3, 2021
#
##########################


CC=gcc
CFLAGS=

example: exmain.c exsum.c exsum.h
		$(CC) exmain.c exsum.c -o example

clean:
		rm example *.o