##########################
#
# HW #1
#
# Garrett McNeill
#
##########################



problem1: stack.c
	gcc stack.c -o prob1

problem2: stackdeux.c
	gcc stackdeux.c -o prob2

answers: stackdeux.c stack.c
	gcc stack.c -o prob1
	gcc stackdeux.c -o prob2


clean:
	rm prob1
	rm prob2 *.o
